/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package smart.warehouse.view;

import com.sun.jmx.snmp.UserAcl;
import java.awt.event.ItemListener;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;
import java.util.concurrent.TimeUnit;
import javafx.fxml.Initializable;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
//import smart.warehouse.bin.DashboardForm;
import smart.warehouse.bo.BoFactory;
import smart.warehouse.bo.BoTypes;
import smart.warehouse.bo.custom.StorageBO;
import smart.warehouse.bo.custom.UserBO;
import smart.warehouse.bo.exception.NotFoundException;
import smart.warehouse.dto.ReturnDTO;
import smart.warehouse.dto.UserDTO;
import smart.warehouse.dto.WarehouseDTO;

/**
 *
 * @author deptp
 */
public class CalculateBillForm extends javax.swing.JFrame {

    /*
     * Creates new form CalculateBillForm
     */
    public CalculateBillForm() {
        initComponents();
        cmbUserNic.removeAllItems();
        
        for (String nic : userBO.getAllNic()) {
           cmbUserNic.addItem(nic); 
        }
        lblDate.setText(String.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(new Date())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbUserNic = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbWarehouseID = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTerminatedStorages = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        btnPayOnAction = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblWarehouseWidth = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnTableAdd = new javax.swing.JButton();
        lblUserName = new javax.swing.JLabel();
        lblWarehouseLength = new javax.swing.JLabel();
        lblWarehouseDes = new javax.swing.JLabel();
        lblWarehousePrice = new javax.swing.JLabel();
        btnTableDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 50)); // NOI18N
        jLabel1.setText("Calculate Bill");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("User NIC");

        cmbUserNic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUserNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUserNicActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Warehouse Code");

        cmbWarehouseID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbWarehouseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbWarehouseIDActionPerformed(evt);
            }
        });

        tblTerminatedStorages.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Warehouse ID", "Reseive Date", "Width", "Length", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTerminatedStorages);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Terminated Storages");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Total Price");

        lblTotalPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnPayOnAction.setBackground(new java.awt.Color(0, 153, 255));
        btnPayOnAction.setText("Pay");
        btnPayOnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayOnActionActionPerformed(evt);
            }
        });

        btnDashboard.setBackground(new java.awt.Color(255, 51, 102));
        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        lblDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDate.setText("2023-03-23");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Name");

        lblWarehouseWidth.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Width");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Length");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Description");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Price");

        btnTableAdd.setText("Add");
        btnTableAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableAddActionPerformed(evt);
            }
        });

        lblUserName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        lblWarehouseLength.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        lblWarehouseDes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        lblWarehousePrice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        btnTableDelete.setText("Delete");
        btnTableDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTableAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(112, 112, 112)
                            .addComponent(btnTableDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDate))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnPayOnAction, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbUserNic, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblWarehousePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblWarehouseWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbWarehouseID, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(lblWarehouseLength, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(lblWarehouseDes, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbUserNic, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbWarehouseID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblWarehouseWidth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblWarehouseLength, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblWarehouseDes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblWarehousePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTableAdd)
                    .addComponent(btnTableDelete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPayOnAction, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    UserBO userBO= BoFactory.getInstance().getBO(BoTypes.USER);
    StorageBO storageBO= BoFactory.getInstance().getBO(BoTypes.STORAGE);
    double netTotal=0;
    private void btnPayOnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayOnActionActionPerformed
        List<ReturnDTO> returnDTOs=new ArrayList<>();
        int rowCount = tblTerminatedStorages.getRowCount();
        DefaultTableModel defaultTableModel=(DefaultTableModel) tblTerminatedStorages.getModel();
        java.sql.Date date=java.sql.Date.valueOf(lblDate.getText());
        for(int i=0; rowCount>i; i++){
           String warehuseCode=defaultTableModel.getValueAt(i, 0).toString();
           double price=Double.parseDouble(defaultTableModel.getValueAt(i, 4).toString());
           returnDTOs.add(new ReturnDTO(warehuseCode,date,price ));
        }
        if(storageBO.returnWarehouse(returnDTOs)){
            JOptionPane.showMessageDialog(this, "Payment Sucsuss!");
            CalculateBillForm calculateBillForm=new CalculateBillForm();
            calculateBillForm.setVisible(true);
            this.dispose();  
        }else{
            JOptionPane.showMessageDialog(this, "Payment NOT Sucsuss!");
            CalculateBillForm calculateBillForm=new CalculateBillForm();
            calculateBillForm.setVisible(true);
            this.dispose();  
        }
    }//GEN-LAST:event_btnPayOnActionActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        DashboardForm dashboardForm=new DashboardForm();
        dashboardForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnTableAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableAddActionPerformed
        WarehouseDTO warehouseDTO=storageBO.searchWarehouse(cmbWarehouseID.getSelectedItem().toString());
        Object[] data={warehouseDTO.getWarehouseCode(),warehouseDTO.getReseiveDate().toString(),warehouseDTO.getWidth(),warehouseDTO.getLength(),Double.parseDouble(lblWarehousePrice.getText())};
        ((DefaultTableModel)tblTerminatedStorages.getModel()).addRow(data);
        netTotal += Double.parseDouble(lblWarehousePrice.getText());
        lblTotalPrice.setText(String.valueOf(netTotal));
        cmbWarehouseID.removeItem(warehouseDTO.getWarehouseCode());
    }//GEN-LAST:event_btnTableAddActionPerformed

    private void cmbUserNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUserNicActionPerformed
        if(cmbUserNic.getSelectedItem()==null)return;
        
        try{
           UserDTO userDTO=userBO.searchUser(cmbUserNic.getSelectedItem().toString());
            int rowCount = tblTerminatedStorages.getRowCount();
           if(rowCount>0){
               tblTerminatedStorages.setModel(new DefaultTableModel(null,new String[]{"Warehouse id","Receive Date","Width","Length","Price"}));
            }
           lblUserName.setText(userDTO.getName());
           List<WarehouseDTO> warehouseDTOs=new ArrayList<>();
           warehouseDTOs.addAll(userDTO.getWarehouseDTOs());
           cmbWarehouseID.removeAllItems();
           reset();
           for (WarehouseDTO warehouseDTO : warehouseDTOs){
                cmbWarehouseID.addItem(warehouseDTO.getWarehouseCode());
           }  
       }catch(NotFoundException e){
           JOptionPane.showMessageDialog(this, e);
       }
        
    }//GEN-LAST:event_cmbUserNicActionPerformed

    private void cmbWarehouseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbWarehouseIDActionPerformed
       if(cmbWarehouseID.getSelectedItem()==null)return;
       WarehouseDTO warehouseDTO=storageBO.searchWarehouse(cmbWarehouseID.getSelectedItem().toString());
       lblWarehouseLength.setText(Double.toString(warehouseDTO.getLength()) );
       lblWarehouseWidth.setText(Double.toString(warehouseDTO.getWidth()));
       lblWarehouseDes.setText(warehouseDTO.getDescription());
    
       double deference=Double.parseDouble(Long.toString(TimeUnit.DAYS.convert(Math.abs(java.sql.Date.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(new Date())).getTime()-warehouseDTO.getReseiveDate().getTime()), TimeUnit.DAYS)));
  
       if(deference==0){
           lblWarehousePrice.setText(Double.toString(warehouseDTO.getLength()*warehouseDTO.getWidth()*1000));
        }else{
           lblWarehousePrice.setText(Double.toString(warehouseDTO.getLength()*warehouseDTO.getWidth()*1000*deference));
       }
    }//GEN-LAST:event_cmbWarehouseIDActionPerformed

    private void btnTableDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableDeleteActionPerformed
        DefaultTableModel defaultTableModel=(DefaultTableModel) tblTerminatedStorages.getModel();
        if(tblTerminatedStorages.getSelectedRowCount()==1){
            int selectedRow = tblTerminatedStorages.getSelectedRow();
            netTotal -= Double.parseDouble(defaultTableModel.getValueAt(selectedRow, 4).toString());
            lblTotalPrice.setText(String.valueOf(netTotal));
            cmbWarehouseID.addItem(defaultTableModel.getValueAt(selectedRow, 0).toString());
            defaultTableModel.removeRow(tblTerminatedStorages.getSelectedRow());
            JOptionPane.showMessageDialog(rootPane, "Deleted!");
        }else if (tblTerminatedStorages.getRowCount()==0){
               JOptionPane.showMessageDialog(rootPane, "Table Is Empty!");
        }else{
              JOptionPane.showMessageDialog(rootPane, "Please Select one row");
        }
    }//GEN-LAST:event_btnTableDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculateBillForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnPayOnAction;
    private javax.swing.JButton btnTableAdd;
    private javax.swing.JButton btnTableDelete;
    private javax.swing.JComboBox<String> cmbUserNic;
    private javax.swing.JComboBox<String> cmbWarehouseID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblWarehouseDes;
    private javax.swing.JLabel lblWarehouseLength;
    private javax.swing.JLabel lblWarehousePrice;
    private javax.swing.JLabel lblWarehouseWidth;
    private javax.swing.JTable tblTerminatedStorages;
    // End of variables declaration//GEN-END:variables

    private void reset() {
        
        lblWarehouseLength.setText(null);
        lblWarehouseWidth.setText(null);
        lblWarehouseDes.setText(null);
        lblWarehousePrice.setText(null);
    }

  
}
